- name: Disable swappiness
  shell: sh -c 'echo 0 > /proc/sys/vm/swappiness'
  become: yes

- name: Persist disabling of swappiness
  shell: sh -c 'echo "" >> /etc/sysctl.conf'
  become: yes

- name: Copy disable-thp script
  copy:
    src: disable-thp
    dest: /etc/init.d/disable-thp
    mode: 0755
  become: yes

- name: Start disable-thp
  service: 
    name: disable-thp
    state: started
    enabled: yes
  become: yes
