---
- name: install python-pip
  package:
    name: python-pip
    state: present
  become: yes

- name: ensure docker-py package exists
  pip:
    name: docker-py
    state: present
  become: yes

- name: ensure couchbase is running in docker
  docker_container:
    name: "couchbase"
    image: "couchbase/server:{{ couchbase_version }}"
    volumes:
      - "{{ couchbase_docker_volume_dir }}:/opt/couchbase/var"
    published_ports: "{{ couchbase_ports }}"
  become: yes

- name: wait for Couchbase API port
  wait_for: { port: 8091 }

- name: wait for GUI to launch
  wait_for: { timeout: 15 }

    
