---
- name: ensure docker package exists
  pip:
    name: docker
    state: present
    extra_args: --user
  when: ansible_user != "root"

- name: ensure docker package exists
  pip:
    name: docker
    state: present
  when: ansible_user == "root"

- name: ensure couchbase is running in docker
  docker_container:
    name: "couchbase"
    image: "couchbase/server:{{ couchbase_version }}"
    volumes:
      - "{{ couchbase_docker_volume_dir }}:/opt/couchbase/var"
    exposed_ports: "{{ couchbase_ports }}"

- name: wait for Couchbase API port
  wait_for: { port: 8091 }

- name: wait for GUI to launch
  wait_for: { timeout: 15 }

    
